services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: barsgroup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - barsgroup-postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d barsgroup" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Frontend/WebApplication1/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=barsgroup;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5080:8080"
    networks:
      - gateway-network

  api-gateway:
    build:
      context: ./ApiGateaway
      dockerfile: APIGateaway.API/Dockerfile
    container_name: api_gateway
    ports:
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5005
      - ASPNETCORE_URLS=http://+:5005
      - ConnectionStrings__Redis=redis-cache:6379,password=SecretRedisPass123!,defaultDatabase=0
      - Keycloak__Authority=http://keycloak:8080/realms/hr-platform
      - Keycloak__ClientId=api-gateway
      - Keycloak__ClientSecret=fReUqrCjHSE49VLEceItCza8XSeOrowB
    depends_on:
      redis-cache:
        condition: service_healthy
    networks:
      - gateway-network

  redis-cache:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --requirepass SecretRedisPass123!
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "SecretRedisPass123!", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - gateway-network

  test-ad:
    image: osixia/openldap:1.5.0
    container_name: local_ad
    environment:
      LDAP_ORGANISATION: "Kazan Corp"
      LDAP_DOMAIN: "company.local"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
    volumes:
      - ./ApiGateaway/ldif_data:/container/environment/01-custom
    networks:
      - gateway-network

  test-ad-admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: local_ad_ui
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "test-ad"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "6480:80"
    depends_on:
      - test-ad
    networks:
      - gateway-network

  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    networks:
      - gateway-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak_server
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      LDAP_ADMIN_PASSWORD: "adminpassword"
      API_GATEWAY_CLIENT_SECRET: "fReUqrCjHSE49VLEceItCza8XSeOrowB"
    ports:
      - "8080:8080"
    volumes:
      - ./ApiGateaway/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./ApiGateaway/keycloak-theme/hr-theme:/opt/keycloak/themes/hr-theme
    depends_on:
      - keycloak-db
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge

volumes:
  barsgroup-postgres: